version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c", "poetry install && exec poetry run app"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
